"""simplify project status, remove is_archived

Revision ID: 639723473e43
Revises: 617b5d6868b5
Create Date: 2026-07-10 12:31:25.248904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '639723473e43'
down_revision: Union[str, None] = '617b5d6868b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_archived')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
